version: '3.9'

services:

  postgres:
    container_name: ama-postgres
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
